services:

  frontend:
    build:
      context: ./frontend
    container_name: file-frontend
    ports:
      - "4200:80"
    depends_on:
      - api

  api:
    build:
      context: ./backend/api
    container_name: file-api
    ports:
      - "3000:3000"
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./uploads:/app/uploads


  worker:
    build:
      context: ./backend/worker
    container_name: file-worker
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBITMQ_URL: amqp://rabbitmq:5672
    volumes:
      - ./uploads:/app/uploads


  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5